In [4]:
import numpy as np
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor

LinearRegression()

In [5]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
y = np.array([3,4,6,2,7,18,23,12,13,16])
y

array([ 3,  4,  6,  2,  7, 18, 23, 12, 13, 16])

In [9]:
regressor.fit(x.reshape(-1,1),y)


LinearRegression()

In [10]:
regressor.intercept_


2.654545454545457

In [11]:
regressor.coef_

array([1.72121212])